# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'intro_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QCommandLinkButton, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QPushButton, QRadioButton,
    QSizePolicy, QStackedWidget, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(793, 327)
        self.actionNuevo_Usuario = QAction(MainWindow)
        self.actionNuevo_Usuario.setObjectName(u"actionNuevo_Usuario")
        self.actionCambiar_Usuario = QAction(MainWindow)
        self.actionCambiar_Usuario.setObjectName(u"actionCambiar_Usuario")
        self.actionJerarqu_as = QAction(MainWindow)
        self.actionJerarqu_as.setObjectName(u"actionJerarqu_as")
        self.actionAlarmas = QAction(MainWindow)
        self.actionAlarmas.setObjectName(u"actionAlarmas")
        self.actionAjustes = QAction(MainWindow)
        self.actionAjustes.setObjectName(u"actionAjustes")
        self.actionImportar_Exportar = QAction(MainWindow)
        self.actionImportar_Exportar.setObjectName(u"actionImportar_Exportar")
        self.actionB_squeda = QAction(MainWindow)
        self.actionB_squeda.setObjectName(u"actionB_squeda")
        self.actionHistorial_Actividad = QAction(MainWindow)
        self.actionHistorial_Actividad.setObjectName(u"actionHistorial_Actividad")
        self.actionEstado_de_Sistema = QAction(MainWindow)
        self.actionEstado_de_Sistema.setObjectName(u"actionEstado_de_Sistema")
        self.actionReporte_Diario_Mensual = QAction(MainWindow)
        self.actionReporte_Diario_Mensual.setObjectName(u"actionReporte_Diario_Mensual")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 50, 791, 221))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.groupBox_temporizador = QGroupBox(self.page)
        self.groupBox_temporizador.setObjectName(u"groupBox_temporizador")
        self.groupBox_temporizador.setGeometry(QRect(290, 110, 241, 101))
        self.groupBox_temporizador.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe UI\";")
        self.pushButton_reset_timer = QPushButton(self.groupBox_temporizador)
        self.pushButton_reset_timer.setObjectName(u"pushButton_reset_timer")
        self.pushButton_reset_timer.setGeometry(QRect(10, 50, 91, 24))
        self.pushButton_reset_timer.setStyleSheet(u"background-color: rgb(170, 85, 255);\n"
"font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_timer = QPlainTextEdit(self.groupBox_temporizador)
        self.plainTextEdit_timer.setObjectName(u"plainTextEdit_timer")
        self.plainTextEdit_timer.setGeometry(QRect(130, 40, 61, 41))
        self.label = QLabel(self.groupBox_temporizador)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 50, 31, 31))
        self.groupBox_cambio_variable = QGroupBox(self.page)
        self.groupBox_cambio_variable.setObjectName(u"groupBox_cambio_variable")
        self.groupBox_cambio_variable.setGeometry(QRect(10, 110, 271, 101))
        self.groupBox_cambio_variable.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe UI\";")
        self.pushButton_incrementar_variable_1 = QPushButton(self.groupBox_cambio_variable)
        self.pushButton_incrementar_variable_1.setObjectName(u"pushButton_incrementar_variable_1")
        self.pushButton_incrementar_variable_1.setGeometry(QRect(20, 30, 131, 24))
        self.pushButton_incrementar_variable_1.setStyleSheet(u"background-color: rgb(0, 0, 255);\n"
"font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_variable_1 = QPlainTextEdit(self.groupBox_cambio_variable)
        self.plainTextEdit_variable_1.setObjectName(u"plainTextEdit_variable_1")
        self.plainTextEdit_variable_1.setGeometry(QRect(190, 40, 61, 41))
        self.pushButton_decrementar_variable_1 = QPushButton(self.groupBox_cambio_variable)
        self.pushButton_decrementar_variable_1.setObjectName(u"pushButton_decrementar_variable_1")
        self.pushButton_decrementar_variable_1.setGeometry(QRect(20, 70, 131, 24))
        self.pushButton_decrementar_variable_1.setStyleSheet(u"background-color: rgb(255, 85, 255);\n"
"font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_fondo_formulario = QGroupBox(self.page)
        self.groupBox_fondo_formulario.setObjectName(u"groupBox_fondo_formulario")
        self.groupBox_fondo_formulario.setGeometry(QRect(10, 20, 361, 81))
        self.groupBox_fondo_formulario.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe UI\";")
        self.pushButton_fondo_azul = QPushButton(self.groupBox_fondo_formulario)
        self.pushButton_fondo_azul.setObjectName(u"pushButton_fondo_azul")
        self.pushButton_fondo_azul.setGeometry(QRect(50, 40, 75, 24))
        self.pushButton_fondo_azul.setStyleSheet(u"background-color: rgb(0, 0, 255);\n"
"font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_fondo_verde = QPushButton(self.groupBox_fondo_formulario)
        self.pushButton_fondo_verde.setObjectName(u"pushButton_fondo_verde")
        self.pushButton_fondo_verde.setGeometry(QRect(150, 40, 75, 24))
        self.pushButton_fondo_verde.setStyleSheet(u"background-color: rgb(0, 170, 0);\n"
"font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_fondo_violeta = QPushButton(self.groupBox_fondo_formulario)
        self.pushButton_fondo_violeta.setObjectName(u"pushButton_fondo_violeta")
        self.pushButton_fondo_violeta.setGeometry(QRect(250, 40, 75, 24))
        self.pushButton_fondo_violeta.setStyleSheet(u"background-color: rgb(170, 85, 255);\n"
"font: 700 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.groupBox_temporizador_2 = QGroupBox(self.page)
        self.groupBox_temporizador_2.setObjectName(u"groupBox_temporizador_2")
        self.groupBox_temporizador_2.setGeometry(QRect(540, 110, 241, 101))
        self.groupBox_temporizador_2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe UI\";")
        self.label_carga_valor = QLabel(self.groupBox_temporizador_2)
        self.label_carga_valor.setObjectName(u"label_carga_valor")
        self.label_carga_valor.setGeometry(QRect(140, 40, 71, 31))
        self.label_carga_valor.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_carga_valor = QLineEdit(self.groupBox_temporizador_2)
        self.lineEdit_carga_valor.setObjectName(u"lineEdit_carga_valor")
        self.lineEdit_carga_valor.setGeometry(QRect(30, 40, 71, 41))
        self.groupBox_intermitente = QGroupBox(self.page)
        self.groupBox_intermitente.setObjectName(u"groupBox_intermitente")
        self.groupBox_intermitente.setGeometry(QRect(380, 20, 241, 81))
        self.groupBox_intermitente.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe UI\";")
        self.label_warning_1 = QLabel(self.groupBox_intermitente)
        self.label_warning_1.setObjectName(u"label_warning_1")
        self.label_warning_1.setGeometry(QRect(10, 20, 101, 51))
        self.label_warning_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_warning_2 = QLabel(self.groupBox_intermitente)
        self.label_warning_2.setObjectName(u"label_warning_2")
        self.label_warning_2.setGeometry(QRect(130, 20, 101, 51))
        self.label_warning_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.radioButton_panel_rosa = QRadioButton(self.page_2)
        self.radioButton_panel_rosa.setObjectName(u"radioButton_panel_rosa")
        self.radioButton_panel_rosa.setGeometry(QRect(50, 30, 121, 20))
        self.radioButton_panel_negro = QRadioButton(self.page_2)
        self.radioButton_panel_negro.setObjectName(u"radioButton_panel_negro")
        self.radioButton_panel_negro.setGeometry(QRect(50, 70, 131, 20))
        self.label_panel = QLabel(self.page_2)
        self.label_panel.setObjectName(u"label_panel")
        self.label_panel.setGeometry(QRect(180, 30, 131, 141))
        self.label_panel.setStyleSheet(u"background-color: rgb(255, 170, 127);")
        self.radioButton_panel_naranja = QRadioButton(self.page_2)
        self.radioButton_panel_naranja.setObjectName(u"radioButton_panel_naranja")
        self.radioButton_panel_naranja.setGeometry(QRect(50, 110, 131, 20))
        self.checkBox_panel_1 = QCheckBox(self.page_2)
        self.checkBox_panel_1.setObjectName(u"checkBox_panel_1")
        self.checkBox_panel_1.setGeometry(QRect(430, 30, 111, 20))
        self.checkBox_panel_2 = QCheckBox(self.page_2)
        self.checkBox_panel_2.setObjectName(u"checkBox_panel_2")
        self.checkBox_panel_2.setGeometry(QRect(430, 70, 111, 20))
        self.checkBox__panel_3 = QCheckBox(self.page_2)
        self.checkBox__panel_3.setObjectName(u"checkBox__panel_3")
        self.checkBox__panel_3.setGeometry(QRect(430, 110, 111, 20))
        self.label_panel_1 = QLabel(self.page_2)
        self.label_panel_1.setObjectName(u"label_panel_1")
        self.label_panel_1.setGeometry(QRect(560, 30, 201, 31))
        self.label_panel_1.setStyleSheet(u"background-color: rgb(170, 255, 0);")
        self.label_panel_2 = QLabel(self.page_2)
        self.label_panel_2.setObjectName(u"label_panel_2")
        self.label_panel_2.setGeometry(QRect(560, 70, 201, 31))
        self.label_panel_2.setStyleSheet(u"background-color: rgb(0, 255, 127);")
        self.label_panel_3 = QLabel(self.page_2)
        self.label_panel_3.setObjectName(u"label_panel_3")
        self.label_panel_3.setGeometry(QRect(560, 110, 201, 31))
        self.label_panel_3.setStyleSheet(u"background-color: rgb(0, 170, 0);")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_imagen = QLabel(self.page_3)
        self.label_imagen.setObjectName(u"label_imagen")
        self.label_imagen.setGeometry(QRect(300, 30, 191, 161))
        self.stackedWidget.addWidget(self.page_3)
        self.pushButton_cerrar_app = QPushButton(self.centralwidget)
        self.pushButton_cerrar_app.setObjectName(u"pushButton_cerrar_app")
        self.pushButton_cerrar_app.setGeometry(QRect(660, 10, 121, 31))
        self.pushButton_cerrar_app.setStyleSheet(u"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 700 11pt \"Segoe UI\";")
        self.commandLinkButton_go_next = QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_go_next.setObjectName(u"commandLinkButton_go_next")
        self.commandLinkButton_go_next.setGeometry(QRect(610, 10, 31, 41))
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoNext))
        self.commandLinkButton_go_next.setIcon(icon)
        self.commandLinkButton_go_prev = QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_go_prev.setObjectName(u"commandLinkButton_go_prev")
        self.commandLinkButton_go_prev.setGeometry(QRect(530, 10, 31, 41))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoPrevious))
        self.commandLinkButton_go_prev.setIcon(icon1)
        self.commandLinkButton_go_home = QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_go_home.setObjectName(u"commandLinkButton_go_home")
        self.commandLinkButton_go_home.setGeometry(QRect(570, 10, 31, 41))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoHome))
        self.commandLinkButton_go_home.setIcon(icon2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 793, 22))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menuUsuarios = QMenu(self.menubar)
        self.menuUsuarios.setObjectName(u"menuUsuarios")
        self.menuReportes = QMenu(self.menubar)
        self.menuReportes.setObjectName(u"menuReportes")
        self.menuConsultas = QMenu(self.menubar)
        self.menuConsultas.setObjectName(u"menuConsultas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuUsuarios.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())
        self.menuArchivo.addAction(self.actionAjustes)
        self.menuArchivo.addAction(self.actionImportar_Exportar)
        self.menuUsuarios.addAction(self.actionNuevo_Usuario)
        self.menuUsuarios.addAction(self.actionCambiar_Usuario)
        self.menuUsuarios.addAction(self.actionJerarqu_as)
        self.menuReportes.addAction(self.actionAlarmas)
        self.menuReportes.addAction(self.actionReporte_Diario_Mensual)
        self.menuConsultas.addAction(self.actionB_squeda)
        self.menuConsultas.addAction(self.actionHistorial_Actividad)
        self.menuConsultas.addAction(self.actionEstado_de_Sistema)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNuevo_Usuario.setText(QCoreApplication.translate("MainWindow", u"Nuevo Usuario", None))
        self.actionCambiar_Usuario.setText(QCoreApplication.translate("MainWindow", u"Cambiar Usuario", None))
        self.actionJerarqu_as.setText(QCoreApplication.translate("MainWindow", u"Jerarqu\u00edas", None))
        self.actionAlarmas.setText(QCoreApplication.translate("MainWindow", u"Generar PDF", None))
        self.actionAjustes.setText(QCoreApplication.translate("MainWindow", u"Ajustes", None))
        self.actionImportar_Exportar.setText(QCoreApplication.translate("MainWindow", u"Importar/Exportar Datos", None))
        self.actionB_squeda.setText(QCoreApplication.translate("MainWindow", u"B\u00fasqueda", None))
        self.actionHistorial_Actividad.setText(QCoreApplication.translate("MainWindow", u"Historial Actividad", None))
        self.actionEstado_de_Sistema.setText(QCoreApplication.translate("MainWindow", u"Estado del Sistema", None))
        self.actionReporte_Diario_Mensual.setText(QCoreApplication.translate("MainWindow", u"Reporte Diario/Mensual", None))
        self.groupBox_temporizador.setTitle(QCoreApplication.translate("MainWindow", u"TEMPORIZADOR", None))
        self.pushButton_reset_timer.setText(QCoreApplication.translate("MainWindow", u"RESETEAR", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"seg.", None))
        self.groupBox_cambio_variable.setTitle(QCoreApplication.translate("MainWindow", u"CAMBIO VARIABLE", None))
        self.pushButton_incrementar_variable_1.setText(QCoreApplication.translate("MainWindow", u"INCREMENTAR", None))
        self.pushButton_decrementar_variable_1.setText(QCoreApplication.translate("MainWindow", u"DECREMENTAR", None))
        self.groupBox_fondo_formulario.setTitle(QCoreApplication.translate("MainWindow", u"FONDO DEL FORMULARIO", None))
        self.pushButton_fondo_azul.setText(QCoreApplication.translate("MainWindow", u"AZUL", None))
        self.pushButton_fondo_verde.setText(QCoreApplication.translate("MainWindow", u"VERDE", None))
        self.pushButton_fondo_violeta.setText(QCoreApplication.translate("MainWindow", u"VIOLETA", None))
        self.groupBox_temporizador_2.setTitle(QCoreApplication.translate("MainWindow", u"CARGA VALOR", None))
        self.label_carga_valor.setText(QCoreApplication.translate("MainWindow", u"Valor", None))
        self.groupBox_intermitente.setTitle(QCoreApplication.translate("MainWindow", u"INTERMITENTE", None))
        self.label_warning_1.setText(QCoreApplication.translate("MainWindow", u"WARNING 1", None))
        self.label_warning_2.setText(QCoreApplication.translate("MainWindow", u"WARNING 2", None))
        self.radioButton_panel_rosa.setText(QCoreApplication.translate("MainWindow", u"Panel ROSA", None))
        self.radioButton_panel_negro.setText(QCoreApplication.translate("MainWindow", u"Panel NEGRO", None))
        self.label_panel.setText("")
        self.radioButton_panel_naranja.setText(QCoreApplication.translate("MainWindow", u"Panel Naranja", None))
        self.checkBox_panel_1.setText(QCoreApplication.translate("MainWindow", u"Mostrar panel 1", None))
        self.checkBox_panel_2.setText(QCoreApplication.translate("MainWindow", u"Mostrar panel 2", None))
        self.checkBox__panel_3.setText(QCoreApplication.translate("MainWindow", u"Mostrar panel 3", None))
        self.label_panel_1.setText("")
        self.label_panel_2.setText("")
        self.label_panel_3.setText("")
        self.label_imagen.setText("")
        self.pushButton_cerrar_app.setText(QCoreApplication.translate("MainWindow", u"CERRAR APP", None))
        self.commandLinkButton_go_next.setText("")
        self.commandLinkButton_go_prev.setText("")
        self.commandLinkButton_go_home.setText("")
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
        self.menuUsuarios.setTitle(QCoreApplication.translate("MainWindow", u"Usuarios", None))
        self.menuReportes.setTitle(QCoreApplication.translate("MainWindow", u"Reportes", None))
        self.menuConsultas.setTitle(QCoreApplication.translate("MainWindow", u"Consultas", None))
    # retranslateUi

